ALTER TABLE "Project" ADD COLUMN "bizPmId" TEXT;
ALTER TABLE "Task" ADD COLUMN "devPlId" TEXT;
ALTER TABLE "Project" ADD CONSTRAINT "Project_bizPmId_fkey" FOREIGN KEY ("bizPmId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_devPlId_fkey" FOREIGN KEY ("devPlId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
